workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    xapi:
        inputs:
            - location: source/sdks.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/dailypay/dailypay/xapi
targets:
    csharp-8:
        target: csharp
        source: xapi
        output: generated/sdk
        codeSamples:
            output: codeSamples.yaml
            registry:
                location: registry.speakeasyapi.dev/dailypay/dailypay/xapi-csharp-code-samples