//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace DailyPay.SDK.DotNet8.Models.Components
{
    using DailyPay.SDK.DotNet8.Models.Components;
    using DailyPay.SDK.DotNet8.Utils;
    using Newtonsoft.Json;
    
    /// <summary>
    /// Returns details about an organization.
    /// </summary>
    public class OrganizationData
    {

        [JsonProperty("data")]
        public OrganizationResource Data { get; set; } = default!;
    }
}