name: Release Please
on:
  push:
    branches:
      - main
      - DEVREL-642

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          manifest-file: ./src/DailyPay/SDK/DotNet8/DailyPay.SDK.DotNet8.csproj