name: "Scan"

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write

jobs:
  scan:
    uses: ./.github/workflows/reusable-scan.yaml
    secrets: inherit
    with:
      branch_name: ${{ github.event_name == 'pull_request' && github.base_ref || 'main' }}

